Source/TennisClub2/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TennisClub2.Models;

namespace TennisClub2.Controllers
{
    public class PlayersController : Controller
    {
        // GET: user
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            using (var Database = new BlogDbContext())
            {
                var Players = Database.Users.ToList();
                                                      
                return View(Players);
            }
        }
    }
}

Source/TennisClub2/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TennisClub2.Models;

namespace TennisClub2.Controllers
{
    public class ResultsController : Controller
    {
     
    
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            using (var Database = new BlogDbContext())
            {
                var Players = Database.Users.ToList();

                return View(Players);
            }
        }
    }
}

Source/TennisClub2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Тенис клуб</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IT Тенис клуб", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">


                    <li>@Html.ActionLink("Контакти", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Клубове", "Clubs", "Home")</li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Играчи", "Players", "Home")</li>
                        <li>@Html.ActionLink("Резултати", "Results", "Home")</li>

                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="pull-right">
            <p>&copy; @DateTime.Now.Year Христо Чорбаджийски</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>